const capitalizeWords = (str) => {
  return str
    ?.split(" ")
    ?.map((word) => word?.charAt(0)?.toUpperCase() + word?.slice(1))
    ?.join(" ");
};

const customStyles = {
  content: {
    top: "50%",
    left: "50%",
    right: "auto",
    bottom: "auto",
    marginRight: "-50%",
    transform: "translate(-50%, -50%)",
  },
};

const stopWords = [
  "a",
  "about",
  "above",
  "after",
  "again",
  "against",
  "all",
  "am",
  "an",
  "and",
  "any",
  "are",
  "aren't",
  "as",
  "at",
  "be",
  "because",
  "been",
  "before",
  "being",
  "below",
  "between",
  "both",
  "but",
  "by",
  "can't",
  "cannot",
  "could",
  "couldn't",
  "did",
  "didn't",
  "do",
  "does",
  "doesn't",
  "doing",
  "don't",
  "down",
  "during",
  "each",
  "few",
  "for",
  "from",
  "further",
  "had",
  "hadn't",
  "has",
  "hasn't",
  "have",
  "haven't",
  "having",
  "he",
  "he'd",
  "he'll",
  "he's",
  "her",
  "here",
  "here's",
  "hers",
  "herself",
  "him",
  "himself",
  "his",
  "how",
  "how's",
  "i",
  "i'd",
  "i'll",
  "i'm",
  "i've",
  "if",
  "in",
  "into",
  "is",
  "isn't",
  "it",
  "it's",
  "its",
  "itself",
  "let's",
  "me",
  "more",
  "most",
  "mustn't",
  "my",
  "myself",
  "no",
  "nor",
  "not",
  "of",
  "off",
  "on",
  "once",
  "only",
  "or",
  "other",
  "ought",
  "our",
  "ours",
  "ourselves",
  "out",
  "over",
  "own",
  "same",
  "shan't",
  "she",
  "she'd",
  "she'll",
  "she's",
  "should",
  "shouldn't",
  "so",
  "some",
  "such",
  "than",
  "that",
  "that's",
  "the",
  "their",
  "theirs",
  "them",
  "themselves",
  "then",
  "there",
  "there's",
  "these",
  "they",
  "they'd",
  "they'll",
  "they're",
  "they've",
  "this",
  "those",
  "through",
  "to",
  "too",
  "under",
  "until",
  "up",
  "very",
  "was",
  "wasn't",
  "we",
  "we'd",
  "we'll",
  "we're",
  "we've",
  "were",
  "weren't",
  "what",
  "what's",
  "when",
  "when's",
  "where",
  "where's",
  "which",
  "while",
  "who",
  "who's",
  "whom",
  "why",
  "why's",
  "with",
  "won't",
  "would",
  "wouldn't",
  "you",
  "you'd",
  "you'll",
  "you're",
  "you've",
  "your",
  "yours",
  "yourself",
  "yourselves",
];

const transporterOptions = {
  host: "smtp.gmail.com",
  port: 465,
  secure: true,
  auth: {
    user: "collegetsainfo@gmail.com@gmail.com",
    pass: "mqkukeayecsdknzc",
  },
  tls: {
    rejectUnauthorized: false,
  },
};

const mailOptions = (to, type, postData) => {
  let subject;
  let html;
  console.log(postData);
  if (type === "free-counseling") {
    subject = "You are Successfully Applied Free Counsling!";
    html = `<h4>Hi ${to}</h4>
   `;
  } else if (type === "new-post") {
    subject = "Check Out Our Latest Post on FindbestOne! 🌟";
    html = `<h1><a href=${postData?.pageUrl}>${postData?.blogData?.title}</a></h1>
    <p>${postData?.blogData?.description}</p>
    <p><a href=${postData?.pageUrl}>View More...</a></p>
    <a href=${postData?.pageUrl}><img src=${postData?.blogData?.titleImage}/></a>
    <p>Thank you for being part of our community. We can't wait to hear what you think!</p>
    <p>Warm regards,</p>
    <b>The FindbestOne Team</b>`;
  }

  const options = {
    from: "collegetsainfo@gmail.com@gmail.com",
    to: to,
    subject: subject,
    html: html,
  };
  return options;
};

export {
  capitalizeWords,
  customStyles,
  stopWords,
  transporterOptions,
  mailOptions,
};